version: "3.8"
services:
    node-app:
        env_file: ".env"
        build:
            context: .
            args:
                NODE_ENV: development
        volumes:
            - ./:/app
            - /app/node_modules
        command: ["npm", "run", "start:dev"]

    mongo:
        restart: always
        env_file: ".env"
