version: "3.8"
services:
    node-app:
        build:
            context: .
        ports:
            - "3000:3000"
        environment:
            - PORT=3000
        depends_on:
            - mongo

    mongo:
        env_file: ".env"
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongo-db:/data/db

volumes:
    mongo-db:
